## K-Nearest Neighbors

In [30]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from collections import Counter

In [31]:
iris =  datasets.load_iris() 
X = iris.data
y = iris.target

In [32]:
print(X[:3])
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [33]:
 x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [34]:
print( len(x_test))
print(y_test[:3])

30
[1 2 1]


<img src='imgs/diagram_euclidean_manhattan_distance_metrics.png'>
<img src='imgs/euclidean_manhattan.jpg'>

In [35]:
def euclidean(x, x2):
    sum=0
    for ix,ix2 in zip(x,x2):
        sum+=(ix-ix2)**2
    return np.sqrt(sum)

In [36]:
def manhattan(x, x2):
    sum=0
    for ix,ix2 in zip(x,x2):
        sum+=abs(ix-ix2)
    return sum

In [37]:
euclidean([0,0], [3,4])

5.0

In [38]:
manhattan([0,0], [3,4])

7

In [39]:
# xt=[6.7, 3.3, 5.7, 2.1]
xt=[5.1, 3., 4.2, 1.5]

In [41]:
dist={}
for i, x in enumerate(x_train):
    ed=euclidean(x, xt)
#     ed=manhattan(x, xt)
    dist[i]=ed

In [42]:
print(dist)

{0: 3.5411862419251547, 1: 3.1937438845342627, 2: 3.0610455730027937, 3: 0.6708203932499374, 4: 1.0148891565092222, 5: 1.8708286933869704, 6: 3.0610455730027937, 7: 3.146426544510455, 8: 1.009950493836208, 9: 1.244989959798873, 10: 3.093541659651604, 11: 1.0816653826391966, 12: 1.3379088160259653, 13: 2.012461179749811, 14: 0.7280109889280523, 15: 0.7000000000000002, 16: 2.947880594596735, 17: 2.9495762407505253, 18: 3.0870698080866266, 19: 2.222611077089287, 20: 1.2409673645990857, 21: 2.4020824298928627, 22: 1.1224972160321829, 23: 2.9086079144497976, 24: 1.8000000000000005, 25: 3.241913015489466, 26: 3.4942810419312296, 27: 2.541653005427767, 28: 3.318132004607412, 29: 3.0397368307141326, 30: 1.349073756323205, 31: 3.057776970284131, 32: 3.1144823004794877, 33: 0.4242640687119289, 34: 0.6403124237432853, 35: 0.6480740698407857, 36: 0.8831760866327848, 37: 3.062678566222711, 38: 2.6720778431774774, 39: 1.322875655532296, 40: 0.6708203932499371, 41: 3.1128764832546763, 42: 1.445683229

In [43]:
sorted_d = sorted(dist.items(), key=lambda kv: kv[1])

In [44]:
print(sorted_d)

[(33, 0.4242640687119289), (75, 0.44721359549995815), (45, 0.5477225575051662), (80, 0.58309518948453), (58, 0.6164414002968975), (34, 0.6403124237432853), (35, 0.6480740698407857), (40, 0.6708203932499371), (3, 0.6708203932499374), (93, 0.6708203932499376), (15, 0.7000000000000002), (14, 0.7280109889280523), (56, 0.8000000000000007), (50, 0.8660254037844387), (95, 0.871779788708135), (36, 0.8831760866327848), (109, 0.9165151389911682), (43, 0.9165151389911683), (67, 0.9539392014169459), (8, 1.009950493836208), (4, 1.0148891565092222), (88, 1.0583005244258363), (11, 1.0816653826391966), (92, 1.1224972160321824), (22, 1.1224972160321829), (83, 1.1269427669584644), (100, 1.126942766958465), (64, 1.174734012447073), (119, 1.2247448713915892), (20, 1.2409673645990857), (9, 1.244989959798873), (57, 1.244989959798873), (107, 1.24899959967968), (71, 1.2569805089976536), (72, 1.3114877048604), (51, 1.319090595827292), (111, 1.3228756555322954), (39, 1.322875655532296), (12, 1.3379088160259653)

In [50]:
k=1
neighbors=[]
for i in range(k):
    neighbors.append(sorted_d[i][0])
print(neighbors)

[33]


In [51]:
classes=[ y_train[i] for i in neighbors]
print(classes)

[1]


In [52]:
count=Counter(classes)
print(count)
keys= list( count.keys() )
print('keys=', keys)
values=list( count.values() )
print('values=',values)

index_of_max_values=values.index(max(values)) 
print('index of max value=', index_of_max_values)
y_hat=keys[index_of_max_values]
print('predict class=',y_hat)

Counter({1: 1})
keys= [1]
values= [1]
index of max value= 0
predict class= 1


In [53]:
def predict(X,y, xt, k):
    #Step_1: calculate distance from all the training instances, track position and distance.
    dist={}
    for i, x in enumerate(x_train):
    #     ed=euclidean(x, xt)
        ed=manhattan(x, xt)
        dist[i]=ed
        
    #step_2: sort the dictionary
    sorted_d = sorted(dist.items(), key=lambda kv: kv[1])
    
    #step_3: choose first k items. we call them neighbors.
    neighbors=[sorted_d[i][0] for i in range(k)]
    
    #step_4: get the labels of the neighbors.
    classes=[ y[i] for i in neighbors]
    
    #step_5: find which class appeared maximum time among the k neighbors.
    count=Counter(classes) 
    keys= list( count.keys() ) 
    values=list( count.values() ) 

    index_of_max_values=values.index(max(values)) 
    y_hat=keys[index_of_max_values]
    return y_hat

In [54]:
predict(x_train,y_train, xt, 3)

1

In [55]:
def KNN(x_train, y_train,  x_test, k):
    ps=[predict(x_train,y_train, xt, k) for xt in x_test] 
    return np.array(ps)   

In [56]:
k=5
ps=KNN(x_train,y_train, x_test, k)
print(ps)
print(y_test)

[1 2 1 0 1 2 1 0 0 2 2 2 2 0 1 0 0 2 2 2 1 0 0 2 2 0 0 0 2 1]
[1 2 1 0 1 2 1 0 0 2 2 2 2 0 1 0 0 2 2 2 1 0 0 1 2 0 0 0 2 1]
