## K-Nearest Neighbors

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from collections import Counter

<img src='imgs\iris-species.png' width=60%>

In [28]:
iris =  datasets.load_iris() 
X = iris.data
y = iris.target

In [30]:
X.shape

(150, 4)

In [31]:
print(X[:5])
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
 x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [10]:
print( len(x_test))
print(y_test[:3])

30
[2 0 2]


<img src='imgs/diagram_euclidean_manhattan_distance_metrics.png'>
<img src='imgs/euclidean_manhattan.jpg'>

In [11]:
def euclidean(x, x2):
    sum=0
    for ix,ix2 in zip(x,x2):
        sum+=(ix-ix2)**2
    return np.sqrt(sum)

In [12]:
def manhattan(x, x2):
    sum=0
    for ix,ix2 in zip(x,x2):
        sum+=abs(ix-ix2)
    return sum

In [13]:
euclidean([0,0], [3,4])

5.0

In [14]:
manhattan([0,0], [3,4])

7

In [15]:
# xt=[6.7, 3.3, 5.7, 2.1]
xt=[5.1, 3., 4.2, 1.5]

In [16]:
dist={}
for i, x in enumerate(x_train):
    ed=euclidean(x, xt)
#     ed=manhattan(x, xt)
    dist[i]=ed

In [17]:
print(dist)

{0: 1.452583904633395, 1: 3.0495901363953815, 2: 0.8124038404635961, 3: 2.428991560298224, 4: 3.024896692450835, 5: 1.4662878298615178, 6: 3.254228019054596, 7: 3.4942810419312296, 8: 1.1269427669584644, 9: 0.8831760866327848, 10: 1.8000000000000005, 11: 3.289376840679706, 12: 0.7280109889280523, 13: 2.247220505424424, 14: 1.9773719933285192, 15: 2.8530685235374214, 16: 3.023243291566195, 17: 1.6792855623746672, 18: 3.0870698080866266, 19: 0.7000000000000002, 20: 3.1796226191169294, 21: 2.1679483388678804, 22: 2.9580398915498085, 23: 1.349073756323205, 24: 3.093541659651604, 25: 3.0610455730027937, 26: 1.244989959798873, 27: 1.0583005244258363, 28: 2.7982137159266447, 29: 2.7092434368288134, 30: 2.3108440016582685, 31: 3.5411862419251547, 32: 3.167017524422623, 33: 0.871779788708135, 34: 1.24899959967968, 35: 1.319090595827292, 36: 1.174734012447073, 37: 3.144837038703278, 38: 3.004995840263344, 39: 2.222611077089287, 40: 1.244989959798873, 41: 1.8165902124584952, 42: 0.670820393249937

In [18]:
sorted_d = sorted(dist.items(), key=lambda kv: kv[1])

In [19]:
print(sorted_d)

[(118, 0.44721359549995815), (88, 0.6164414002968975), (56, 0.6708203932499371), (42, 0.6708203932499374), (114, 0.6708203932499376), (19, 0.7000000000000002), (12, 0.7280109889280523), (63, 0.8000000000000007), (2, 0.8124038404635961), (110, 0.8544003745317535), (92, 0.8660254037844387), (33, 0.871779788708135), (9, 0.8831760866327848), (94, 0.9165151389911682), (99, 0.9165151389911683), (64, 1.009950493836208), (83, 1.0344080432788603), (27, 1.0583005244258363), (90, 1.0630145812734653), (93, 1.0816653826391966), (98, 1.1224972160321829), (8, 1.1269427669584644), (102, 1.126942766958465), (36, 1.174734012447073), (72, 1.2083045973594573), (59, 1.2409673645990857), (26, 1.244989959798873), (40, 1.244989959798873), (34, 1.24899959967968), (77, 1.2569805089976536), (91, 1.30384048104053), (79, 1.3114877048604), (35, 1.319090595827292), (74, 1.3228756555322954), (44, 1.322875655532296), (23, 1.349073756323205), (89, 1.3601470508735445), (116, 1.392838827718412), (109, 1.4177446878757827)

In [26]:
k=3
neighbors=[]
for i in range(k):
    neighbors.append(sorted_d[i][0])
print(neighbors)

[118, 88, 56]


In [27]:
classes=[ y_train[i] for i in neighbors]
print(classes)

[1, 1, 1]


In [52]:
count=Counter(classes)
print(count)
keys= list( count.keys() )
print('keys=', keys)
values=list( count.values() )
print('values=',values)

index_of_max_values=values.index(max(values)) 
print('index of max value=', index_of_max_values)
y_hat=keys[index_of_max_values]
print('predict class=',y_hat)

Counter({1: 1})
keys= [1]
values= [1]
index of max value= 0
predict class= 1


In [53]:
def predict(X,y, xt, k):
    #Step_1: calculate distance from all the training instances, track position and distance.
    dist={}
    for i, x in enumerate(x_train):
    #     ed=euclidean(x, xt)
        ed=manhattan(x, xt)
        dist[i]=ed
        
    #step_2: sort the dictionary
    sorted_d = sorted(dist.items(), key=lambda kv: kv[1])
    
    #step_3: choose first k items. we call them neighbors.
    neighbors=[sorted_d[i][0] for i in range(k)]
    
    #step_4: get the labels of the neighbors.
    classes=[ y[i] for i in neighbors]
    
    #step_5: find which class appeared maximum time among the k neighbors.
    count=Counter(classes) 
    keys= list( count.keys() ) 
    values=list( count.values() ) 

    index_of_max_values=values.index(max(values)) 
    y_hat=keys[index_of_max_values]
    return y_hat

In [54]:
predict(x_train,y_train, xt, 3)

1

In [55]:
def KNN(x_train, y_train,  x_test, k):
    ps=[predict(x_train,y_train, xt, k) for xt in x_test] 
    return np.array(ps)   

In [56]:
k=5
ps=KNN(x_train,y_train, x_test, k)
print(ps)
print(y_test)

[1 2 1 0 1 2 1 0 0 2 2 2 2 0 1 0 0 2 2 2 1 0 0 2 2 0 0 0 2 1]
[1 2 1 0 1 2 1 0 0 2 2 2 2 0 1 0 0 2 2 2 1 0 0 1 2 0 0 0 2 1]
