In [2]:
import numpy as np

### Vector: 1-D array

In [2]:
#Create a vector as a Row
vector_row = np.array([1,2,3])
print(vector_row)

[1 2 3]


In [3]:
#Create vector as a Column
vector_column = np.array([[1],[2],[3]])
print(vector_column)

[[1]
 [2]
 [3]]


In [42]:
#arange([start],stop,[step]) 
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [49]:
lin_arr = np.linspace(0, 10, 5)  #start, stop, number of points evenly spaced
print(lin_arr)

[ 0.   2.5  5.   7.5 10. ]


In [50]:
my_rand = np.random.rand(4)
print(my_rand)

[0.70236102 0.13153759 0.91758206 0.5472845 ]


### Matrix: 2-D array

In [5]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [10]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [3]:
b = np.ones((3,2))    # Create an array of all ones
print(b) 

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
c = np.full((3,2), 8)  # Create a constant array
print(c) 

[[8 8]
 [8 8]
 [8 8]]


In [5]:
d = np.eye(4)         # Create a 2x2 identity matrix
print(d) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e) 

[[0.77571651 0.77016212]
 [0.53253959 0.0984232 ]]


### Selection

In [7]:
#Create a vector as a Row
vector_row = np.array([ 1,2,3,4,5,6 ])
print(vector_row)
#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
# matrix[2][1]
matrix[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [13]:
vector_row[1:3:1]

array([2, 3])

In [16]:
vector_row[:3]

array([1, 2, 3])

In [19]:
vector_row[3:]

array([4, 5, 6])

In [21]:
vector_row[-1]

6

In [18]:


#Select 3rd element of Vector
print(vector_row[2])

#Select 2nd row 2nd column
print(matrix[1,1])
#Select all elements of a vector
print(vector_row[:])
#Select everything up to and including the 3rd element
print(vector_row[:3])
#Select the everything after the 3rd element
print(vector_row[3:])
#Select the last element
print(vector_row[-1])

3
5
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6


In [18]:
#Select the first 2 rows and all the columns of the matrix
print(matrix[:2,:])
#Select all rows and the 2nd column of the matrix
print(matrix[:,1:2])

[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


### Info

In [57]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(matrix.shape)

print(matrix.size)
#View the number of Dimensions(2 in this case)
print(matrix.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
2


In [58]:
matrix.argmax() #index of the highest value in the array 

8

In [59]:
matrix.argmin() #index of the lowest value in the array

0

In [45]:
print(matrix)
print(np.max(matrix))  
print(np.min(matrix))

print(np.max(matrix,axis=0)) #max in each column 
print(np.max(matrix,axis=1)) #max in each row

print('sum:')
print( np.sum(matrix,axis=0) )  # sum along the cols
print( np.sum(matrix,axis=1) )  #sum along the rows

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
[7 8 9]
[3 6 9]
sum:
[12 15 18]
[ 6 15 24]


In [34]:
print(np.max(matrix,axis=1)) #max in each row

[3 6 9]


In [26]:
#Mean
print(np.mean(matrix))
#Standard Dev.
print(np.std(matrix))
#Variance
print(np.var(matrix))

5.0
2.581988897471611
6.666666666666667


In [37]:
#Reshape
print(matrix.reshape(9,1))
#Here -1 says as many columns as needed and 1 row
print(matrix.reshape(1,-1))
#If we provide only 1 value Reshape would return a 1-d array of that length
print(matrix.reshape(9))
#We can also use the Flatten method to convert a matrix to 1-d array
print(matrix.flatten())

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [30]:
#Transpose the matrix
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [31]:
#Calculate the Determinant
print(np.linalg.det(matrix))
#Calculate the Rank
print(np.linalg.matrix_rank(matrix))

0.0
2


In [32]:
# Calculate the Eigenvalues and Eigenvectors of that Matrix
eigenvalues ,eigenvectors=np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### Operation

In [36]:
#Create vector-1
vector_1 = np.array([ 1,2,3 ])
#Create vector-2
vector_2 = np.array([ 4,5,6 ])
#Calculate Dot Product
print(np.dot(vector_1,vector_2))
#Alternatively you can use @ to calculate dot products
print(vector_1 @ vector_2)
print(vector_1.dot(vector_2))

32
32
32


In [38]:
#Create Matrix-1
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
#Create Matrix-2
matrix_2 = np.array([[7,8,9],[4,5,6],[1,2,3]])
#Add the 2 Matrices
print(np.add(matrix_1,matrix_2))
#Subtraction
print(np.subtract(matrix_1,matrix_2))
#Multiplication(Element wise, not Dot Product)
print(matrix_1*matrix_2)

[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]
[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]
[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]


In [39]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,2]])
print(matrix)
#Calculate its inverse
print(np.linalg.inv(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 2]]
[[-1.80952381  0.95238095 -0.14285714]
 [ 1.61904762 -0.9047619   0.28571429]
 [-0.14285714  0.28571429 -0.14285714]]


### Ref.

1. https://becominghuman.ai/an-essential-guide-to-numpy-for-machine-learning-in-python-5615e1758301
2. http://cs231n.github.io/python-numpy-tutorial/
3. https://hackernoon.com/introduction-to-numpy-1-an-absolute-beginners-guide-to-machine-learning-and-data-science-5d87f13f0d51
4. https://towardsdatascience.com/lets-talk-about-numpy-for-datascience-beginners-b8088722309f